### DISCUSSION TITLE
Why doesn't AddConfigStoredInConsul() work as normal Consul config?

### DISCUSSION THREAD

**Discussion by ArchitectAllenGitHub** [ThreeMammals/Ocelot#1762] [Q&A] [answered]
## Expected Behavior / New Feature
The same configuration is used. `AddConfigStoredInConsul()` request 404, Normal if not in use.
Program.cs  It is shown below:
``` C#
using Ocelot.DependencyInjection;
using Ocelot.Middleware;
using Ocelot.Provider.Consul;

var builder = WebApplication.CreateBuilder(args);
builder.Configuration.AddJsonFile("ocelot.json");
builder.Services
    .AddOcelot()
    .AddConsul()
    .AddConfigStoredInConsul();

var app = builder.Build();

app.UseOcelot();

app.Run();
```
ocelot.json It is shown below
``` json
{
"Routes": [
    {
      "UpstreamPathTemplate": "/Ocelot/{url}",
      "UpstreamHttpMethod": [
        "Get",
        "Post"
      ],
      "DownstreamPathTemplate": "/{url}",
      "DownstreamScheme": "http",
      "ServiceName": "MagicCore.API",
      "LoadBalancerOptions": {
        "Type": "RoundRobin"
      }
    }
  ],
  "GlobalConfiguration": {
    "ServiceDiscoveryProvider": {
      "Host": "localhost",
      "Port": 8500
    }
  }
}
```

**Comment by ggnaegi** [comment]
Hello @ArchitectAllenGitHub could you provide more details? Thanks!

**Comment by raman-m** [comment]
> Hello @ArchitectAllenGitHub could you provide more details? Thanks!

@ggnaegi Look at **"ServiceDiscoveryProvider"** options in global config! They have no a **Type** property defined!
I would say, this is border conditions case when no Type in the options, but developer has added Consul via `AddConsul`.
We should substitute default type of discovery provider: `Consul` or `PollConsul`.
To be discussed...

**Comment by raman-m** [comment]
**Second**, our docs for [Load Balancer](https://ocelot.readthedocs.io/en/latest/features/loadbalancer.html) says nothing about coupling Service Discovery vs Load Balancer. The author was confused. We don't explain correct instructions...

**Comment by raman-m** [comment]
> .AddConfigStoredInConsul();

What's the strange method?
Is it from Ocelot code base?
Or, is it a custom author's extension?

**Comment by ggnaegi** [comment]
> > .AddConfigStoredInConsul();
> 
> What's the strange method?
> Is it from Ocelot code base?
> Or, is it a custom author's extension?

@raman-m it's for the consul key value store. You could have dynamic configuration, the ocelot config being stored in consul. It starts an IHostedService instance called FileConfigurationPoller.
https://developer.hashicorp.com/consul/docs/dynamic-app-config/kv
and the funny thing, I'm using it... 😹 

```c#
public static IOcelotBuilder AddConsul(this IOcelotBuilder builder)
    {
        builder.Services
            .AddSingleton(ConsulProviderFactory.Get)
            .AddSingleton<IConsulClientFactory, ConsulClientFactory>()
            .RemoveAll(typeof(IFileConfigurationPollerOptions))
            .AddSingleton<IFileConfigurationPollerOptions, ConsulFileConfigurationPollerOption>();
        return builder;
    }

    public static IOcelotBuilder AddConfigStoredInConsul(this IOcelotBuilder builder)
    {
        builder.Services
            .AddSingleton(ConsulMiddlewareConfigurationProvider.Get)
            .AddHostedService<FileConfigurationPoller>()
            .AddSingleton<IFileConfigurationRepository, ConsulFileConfigurationRepository>();
        return builder;
    }
```

**Comment by ArchitectAllenGitHub** [comment]
@ggnaegi @raman-m 
Thank you for your help.Here's my demo 
https://github.com/ArchitectAllenGitHub/OcelotDemo

**Reply by raman-m** [reply]
Uploading dll files and executable ones is very bad!!!
We are not going to run this exe!

You have to upload source code as solid solution!

**Comment by ggnaegi** [comment]
@ArchitectAllenGitHub could you try a config like this one? like @raman-m mentioned we might have a problem with the configuration since the ServiceDiscoveryProvider type is not defined.
```
"GlobalConfiguration": {
    "ServiceDiscoveryProvider": {
      "Host": "consul",
      "Port": 8500,
      "Type": "PollConsul",
      "PollingInterval": 3600000
    }
  }
```
Ok, I'm using a docker environment, so Host would be localhost or 127.0.0.1 for you ;-)

**Comment by ArchitectAllenGitHub** [comment]
> 你能试试这样的配置吗？如前所述，由于未定义 ServiceDiscoveryProvider 类型，因此我们的配置可能存在问题。
> 
> ```
> "GlobalConfiguration": {
>     "ServiceDiscoveryProvider": {
>       "Host": "consul",
>       "Port": 8500,
>       "Type": "PollConsul",
>       "PollingInterval": 3600000
>     }
>   }
> ```
> 
> 好的，我正在使用 docker 环境，所以 Host 将是 localhost 或 127.0.0.1 ;-）

Following the configuration above, I added the Type and PollingInterval. All else being equal.
The AddConfigStoredInConsul() method is not used

![image](https://github.com/ThreeMammals/Ocelot/assets/66348603/90e8f7cf-31cc-422b-8be8-70a42af06469)

Use the AddConfigStoredInConsul() method 
![image](https://github.com/ThreeMammals/Ocelot/assets/66348603/b560a699-649a-4173-8af3-20a956182707)
![image](https://github.com/ThreeMammals/Ocelot/assets/66348603/763e110f-f1cf-47ff-ab3c-6709407670a4)
The specific json in Consul is as follows
``` json
{
  "Routes": [
    {
      "DownstreamPathTemplate": "/{url}",
      "UpstreamPathTemplate": "/Ocelot/{url}",
      "UpstreamHttpMethod": [
        "Get",
        "Post"
      ],
      "DownstreamHttpMethod": null,
      "AddHeadersToRequest": {},
      "UpstreamHeaderTransform": {},
      "DownstreamHeaderTransform": {},
      "AddClaimsToRequest": {},
      "RouteClaimsRequirement": {},
      "AddQueriesToRequest": {},
      "ChangeDownstreamPathTemplate": {},
      "RequestIdKey": null,
      "FileCacheOptions": {
        "TtlSeconds": 0,
        "Region": null
      },
      "RouteIsCaseSensitive": false,
      "ServiceName": "MagicCore.API",
      "ServiceNamespace": null,
      "DownstreamScheme": "http",
      "QoSOptions": {
        "ExceptionsAllowedBeforeBreaking": 0,
        "DurationOfBreak": 0,
        "TimeoutValue": 0
      },
      "LoadBalancerOptions": {
        "Type": "RoundRobin",
        "Key": null,
        "Expiry": 0
      },
      "RateLimitOptions": {
        "ClientWhitelist": [],
        "EnableRateLimiting": false,
        "Period": null,
        "PeriodTimespan": 0.0,
        "Limit": 0
      },
      "AuthenticationOptions": {
        "AuthenticationProviderKey": null,
        "AllowedScopes": []
      },
      "HttpHandlerOptions": {
        "AllowAutoRedirect": false,
        "UseCookieContainer": false,
        "UseTracing": false,
        "UseProxy": true,
        "MaxConnectionsPerServer": 2147483647
      },
      "DownstreamHostAndPorts": [],
      "UpstreamHost": null,
      "Key": null,
      "DelegatingHandlers": [],
      "Priority": 1,
      "Timeout": 0,
      "DangerousAcceptAnyServerCertificateValidator": false,
      "SecurityOptions": {
        "IPAllowedList": [],
        "IPBlockedList": [],
        "ExcludeAllowedFromBlocked": false
      },
      "DownstreamHttpVersion": null
    }
  ],
  "DynamicRoutes": [],
  "Aggregates": [],
  "GlobalConfiguration": {
    "RequestIdKey": null,
    "ServiceDiscoveryProvider": {
      "Scheme": null,
      "Host": "localhost",
      "Port": 8500,
      "Type": "PollConsul",
      "Token": null,
      "ConfigurationKey": null,
      "PollingInterval": 3600000,
      "Namespace": null
    },
    "RateLimitOptions": {
      "ClientIdHeader": "ClientId",
      "QuotaExceededMessage": null,
      "RateLimitCounterPrefix": "ocelot",
      "DisableRateLimitHeaders": false,
      "HttpStatusCode": 429
    },
    "QoSOptions": {
      "ExceptionsAllowedBeforeBreaking": 0,
      "DurationOfBreak": 0,
      "TimeoutValue": 0
    },
    "BaseUrl": null,
    "LoadBalancerOptions": {
      "Type": null,
      "Key": null,
      "Expiry": 0
    },
    "DownstreamScheme": null,
    "HttpHandlerOptions": {
      "AllowAutoRedirect": false,
      "UseCookieContainer": false,
      "UseTracing": false,
      "UseProxy": true,
      "MaxConnectionsPerServer": 2147483647
    },
    "DownstreamHttpVersion": null
  }
}
```

**Comment by ggnaegi** [comment]
Yeah, but wait a minute, do you have registered your services to consul? Otherwise it's useless... The idea here is the following, you register your services to consul and then you query consul for the service addresses. I have an example here: https://github.com/ggnaegi/SwizlyPeasy.Gateway/blob/master/SwizlyPeasy.Consul/README.md
Then, you can register several service instances to consul and then it will allow the load balancing.

But, @ArchitectAllenGitHub you are right, there is something not consistent here...

**Comment by ArchitectAllenGitHub** [comment]
> Yeah, but wait a minute, do you have registered your services to consul? Otherwise it's useless... The idea here is the following, you register your services to consul and then you query consul for the service addresses. I have an example here: https://github.com/ggnaegi/SwizlyPeasy.Gateway/blob/master/SwizlyPeasy.Consul/README.md Then, you can register several service instances to consul and then it will allow the load balancing.
> 
> But, @ArchitectAllenGitHub you are right, there is something not consistent here...

The service is registered, Ocelot can be forwarded normally without adding the AddConfigStoredInConsul() method. Add this method and it's 404, which is very strange
![image](https://github.com/ThreeMammals/Ocelot/assets/66348603/048918de-e1d1-4e3f-990f-c8e889a5bfa4)

**Comment by raman-m** [comment]
@ArchitectAllenGitHub
Disable `AddConfigStoredInConsul()` for now, remove it. And let's check classic setup of Consul config...

Show us what have you registered in Consul Services?

And, make screenshots of response & HTTP status code of direct connection from Ocelot's machine in Postman tool to your downstream service `MagicCore.API` please.

What is your Ocelot's machine? How did you deploy the machine? How do you host Ocelot app? Is it deployed to Docker image/container or not?

**Comment by ggnaegi** [comment]
@ArchitectAllenGitHub It's very strange, and even more for me since i'm using this in production... 😆 
@ArchitectAllenGitHub And you are starting your ocelot instance on port 8000, right?

**Reply by ArchitectAllenGitHub** [reply]
yes,Port 8000

**Comment by ArchitectAllenGitHub** [comment]
> @ArchitectAllenGitHub Disable `AddConfigStoredInConsul()` for now, remove it. And let's check classic setup of Consul config...
> 
> Show us what have you registered in Consul Services?
> 
> And, make screenshots of response & HTTP status code of direct connection from Ocelot's machine in Postman tool to your downstream service `MagicCore.API` please.
> 
> What is your Ocelot's machine? How did you deploy the machine? How do you host Ocelot app? Is it deployed to Docker image/container or not?


I'm running on Windows.
This is the configuration of the Consul
![image](https://github.com/ThreeMammals/Ocelot/assets/66348603/821329ed-51e7-4773-8229-11ad38d99d62)
![image](https://github.com/ThreeMammals/Ocelot/assets/66348603/7717b053-4ea8-4778-a70d-c86c10ef2603)
This is the case with the request through the Ocelot gateway, you can see if it is clear enough
![image](https://github.com/ThreeMammals/Ocelot/assets/66348603/6d9b3f00-1f05-4dc1-b7d8-8ef645e7b2f4)

**Reply by raman-m** [reply]
Could you switch UI to English please?

You showed us screenshot of different service, not exactly of downstream service which is registered in Consul with `localhost:5075`!!!
Make request from Ocelot's machine to `localhost:5075` API and show us the response plz...

`localhost:8000/ocelot/WeatherForecast`
Is it upstream request, right?

**Reply by ArchitectAllenGitHub** [reply]
Here is the log from Octelot
![image](https://github.com/ThreeMammals/Ocelot/assets/66348603/d1656142-191b-4495-9f92-39e89f472871)
`localhost:8000/ocelot/WeatherForecast` Is it upstream request

**Reply by raman-m** [reply]
🆗 Thank you! It seems classic Consul setup is working.
You can re-enable mentioned method call in DI and try to configure...
Let us know a feedback please...

**Reply by ArchitectAllenGitHub** [reply]
What I'm offering is what you'd like to see? The logs do not have the requested information
![image](https://github.com/ThreeMammals/Ocelot/assets/66348603/79433e49-f3d9-4fa4-813e-a641a2ffc1ce)

**Reply by raman-m** [reply]
> What I'm offering is what you'd like to see? The logs do not have the requested information
> ![image](https://github.com/ThreeMammals/Ocelot/assets/66348603/79433e49-f3d9-4fa4-813e-a641a2ffc1ce)
> 

Can you debug all extension helpers included to the AddConfigStoredInConsul() ?

We have no other options to help you...
We have to debug the solution...
I have no time for that.
I hope, you and Gui will find the root cause in debugging sessions... Good luck!

**Reply by ArchitectAllenGitHub** [reply]
Ok, thanks for the help

**Reply by raman-m** [reply]
We will continue our nice discussion tomorrow...

**Comment by ggnaegi** [comment]
@ArchitectAllenGitHub I will try to reproduce your config and come back to you. ..

**Reply by ArchitectAllenGitHub** [reply]
Okay thanks, I just did a test on windows, combined with 'Consul', and there is no problem with normal use. Add the AddConfigStoredInConsul() method to be problematic

**Reply by raman-m** [reply]
Let's find a root cause together!....
I want to make sure this service extension works fine ..
In case of found bug, we will open a bug-issue...

**Reply by ggnaegi** [reply]
@ArchitectAllenGitHub do you have the source code of your APIs (or at least the Program.cs)? I'm really sorry, but I would like to avoid starting the executables you provided.

**Reply by raman-m** [reply]
> @ArchitectAllenGitHub do you have the source code of your APIs (or at least the Program.cs)? I'm really sorry, but I would like to avoid starting the executables you provided.

@ggnaegi 
Agreed! Stop helping him until the author will upload all source files as a solid workable solution!

Unfortunately, he has local environment only, we cannot use RDC to connect to remote machine and see the solution.

**Reply by ArchitectAllenGitHub** [reply]
Absolutely, this project includes the API and the Ocelot gateway
https://github.com/ArchitectAllenGitHub/MagicCore

**Reply by ggnaegi** [reply]
Ok great @ArchitectAllenGitHub thanks.

**Comment by ggnaegi** [comment, marked as answer]
@ArchitectAllenGitHub 
So, I was a bit lazy, I haven't used your code, but I tried a similar configuration as yours and it's working fine. 
Environment: Windows, Ocelot 20.0.0, RoundRobin load balancer, 2 instances of service SuperTestService. 
That's an excerpt of the ocelot file stored in consul KV-Store:
```yaml
{
      "DownstreamPathTemplate": "/test/v{version}/all-labels-and-options",
      "UpstreamPathTemplate": "/test/v{version}/all-labels-and-options",
      "UpstreamHttpMethod": [
        "GET"
      ],
      "DownstreamHttpMethod": null,
      "AddHeadersToRequest": {},
      "UpstreamHeaderTransform": {},
      "DownstreamHeaderTransform": {},
      "AddClaimsToRequest": {},
      "RouteClaimsRequirement": {},
      "AddQueriesToRequest": {},
      "ChangeDownstreamPathTemplate": {},
      "RequestIdKey": null,
      "FileCacheOptions": {
        "TtlSeconds": 0,
        "Region": null
      },
      "RouteIsCaseSensitive": false,
      "ServiceName": "SuperTestService",
      "ServiceNamespace": null,
      "DownstreamScheme": "http",
      "QoSOptions": {
        "ExceptionsAllowedBeforeBreaking": 0,
        "DurationOfBreak": 0,
        "TimeoutValue": 0
      },
      "LoadBalancerOptions": {
        "Type": "RoundRobin",
        "Key": null,
        "Expiry": 0
      },
      "RateLimitOptions": {
        "ClientWhitelist": [],
        "EnableRateLimiting": true,
        "Period": "1s",
        "PeriodTimespan": 1.0,
        "Limit": 5
      },
      "AuthenticationOptions": {
        "AuthenticationProviderKey": null,
        "AllowedScopes": []
      },
      "HttpHandlerOptions": {
        "AllowAutoRedirect": false,
        "UseCookieContainer": false,
        "UseTracing": false,
        "UseProxy": true,
        "MaxConnectionsPerServer": 2147483647
      },
      "DownstreamHostAndPorts": [],
      "UpstreamHost": null,
      "Key": null,
      "DelegatingHandlers": [],
      "Priority": 1,
      "Timeout": 0,
      "DangerousAcceptAnyServerCertificateValidator": false,
      "SecurityOptions": {
        "IPAllowedList": [],
        "IPBlockedList": [],
        "ExcludeAllowedFromBlocked": false
      },
      "DownstreamHttpVersion": null
    },
...
"DynamicRoutes": [],
  "Aggregates": [],
  "GlobalConfiguration": {
    "RequestIdKey": null,
    "ServiceDiscoveryProvider": {
      "Scheme": null,
      "Host": "consul",
      "Port": 8500,
      "Type": "PollConsul",
      "Token": null,
      "ConfigurationKey": null,
      "PollingInterval": 3600000,
      "Namespace": null
    },
    "RateLimitOptions": {
      "ClientIdHeader": "ClientId",
      "QuotaExceededMessage": null,
      "RateLimitCounterPrefix": "ocelot",
      "DisableRateLimitHeaders": false,
      "HttpStatusCode": 429
    },
    "QoSOptions": {
      "ExceptionsAllowedBeforeBreaking": 0,
      "DurationOfBreak": 0,
      "TimeoutValue": 0
    },
    "BaseUrl": null,
    "LoadBalancerOptions": {
      "Type": null,
      "Key": null,
      "Expiry": 0
    },
    "DownstreamScheme": null,
    "HttpHandlerOptions": {
      "AllowAutoRedirect": false,
      "UseCookieContainer": false,
      "UseTracing": false,
      "UseProxy": true,
      "MaxConnectionsPerServer": 2147483647
    },
    "DownstreamHttpVersion": null
  }
```
