### DISCUSSION TITLE
Cannot assign requested address

### DISCUSSION THREAD

**Discussion by cpiock** [ThreeMammals/Ocelot#1929] [Show and tell]
I have done my first example with oclet with docker. I have 2 images 1 is my ocelot apigateway running on localhost:6002 and one is my api running on localhost:6001

```
  my.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${AuthenticationDB_PROD:-Server=sql.data;Database=AuthenticationDb;User Id=SA;Password=Pass@word}
      - UseCustomizationData=True
      - AzureServiceBusEnabled=False
      - AzureStorageEnabled=False
    ports:
      - "6001:80"  

  apigateway.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - UseCustomizationData=True
      - AzureServiceBusEnabled=False
      - AzureStorageEnabled=False
    ports:
      - "6002:80"`
```
Here my config:
```json
{
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/api/{version}/{everything}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 6001
        }
      ],
      "UpstreamPathTemplate": "/api/auth/{version}/{everything}",
      "UpstreamHttpMethod": []
    }
  ]
```

If I run http://localhost:6001/api/v1/authentication/authenticate everything works fine. But if I call this endpoint trough the apigateway I see in the logs the following error
```
Ocelot.Responder.Middleware.ResponderMiddleware[0]
      requestId: 0HLLV201IGIHI:0000000C, previousRequestId: no previous request id, 
message: 
  Error Code: UnableToCompleteRequestError 
  Message: Error making http request, 
    exception: System.Net.Http.HttpRequestException: Cannot assign requested address
    ---> System.Net.Sockets.SocketException: Cannot assign requested address
```

I see that ocelot is trying to call this url and calling this with postman it works fine
Downstream url is http://localhost:6001/api/v1/authentication/authenticate

I think I made some beginner error but I can't find him
Thanks
