### ISSUE TITLE
After updating to kube 15.0.6, no redirect working

### ISSUE THREAD

**Issue by rakkum** [ThreeMammals/Ocelot#1199]
## Expected Behavior / New Feature
We had 14.0.11 installed for our gateway service running in Azure K8s, version 1.15.7. After updating to 15.0.6 no reroutes are working. There should be no regressions when doing this update.

## Actual Behavior / Motivation for New Feature
Looking at the logs, it shows these errors:  Unable to find service discovery provider for type: kube

Here is the Global config:
`"GlobalConfiguration": {
        "ServiceDiscoveryProvider": {
            "Host": "unused",
            "Port": 443,
            "Token": "unused",
            "Namespace": "XXX",
            "Type": "kube"
        }
    }`

Since we use rbac with least accessabiliy we have the following definition for the access rights.

```
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: XXX
  name: api-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: XXX
  name: service-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services", "endpoints", "pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-services
  namespace: XXX
subjects:
- kind: ServiceAccount
  name: api-serviceaccount
  namespace: XXX
  apiGroup: ""
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: service-reader
  apiGroup: rbac.authorization.k8s.io
```
Any other information thats needed? Everything else we kept the same, its really only the nuget update and the user account changes.

## Steps to Reproduce the Problem

  1. Build a system using 14.x.x for k8s and define a reroute.
  2. Update the kubernetes nuget to 15.06
  3. Verify that the reroute is still working

## Specifications

  - Version: 15.0.6
  - Platform: net core 3.1
  - Subsystem: kube
