### ISSUE TITLE
Not Found (404) Error with Service Discovery - Docker / Consul

### ISSUE THREAD

**Issue by johha86** [ThreeMammals/Ocelot#1329]
## Expected Behavior 
Reroute to the downstream path.

## Actual Behavior
Any request return a **Not Found Error(404)** with the following message in the VS output window:
```
warn: Ocelot.Responder.Middleware.ResponderMiddleware[0]  requestId: 0HM2E7R13PE70:00000001, previousRequestId: no previous request id, message: Error Code: ServicesAreEmptyError Message: services were empty for SharepointAPI errors found in ResponderMiddleware. Setting error response for request path:/File, request method: GET

Ocelot.Responder.Middleware.ResponderMiddleware: Warning: requestId: 0HM2E7R13PE70:00000001, previousRequestId: no previous request id, message: Error Code: ServicesAreEmptyError Message: services were empty for SharepointAPI errors found in ResponderMiddleware. Setting error response for request path:/File, request method: GET
```

## Steps to Reproduce the Problem

I created two ASP Net Core Web API projects. The first one implement a API Gateway using Ocelot with Consul and the second one is a simple Web API Service with a endpoint routed to **/api/v1/File**. Both project are initialized by a **docker composer** project

  1. Ocelot.json file:

 ```json
"Routes": [
    {
      "DownstreamPathTemplate": "/api/v1/File",      
      "DownstreamScheme": "http",
      "UpstreamPathTemplate": "/File",
      "UpstreamHttpMethod": [ "Get" ],
      "ServiceName": "SharepointAPI",
      "LoadBalancerOptions": {
        "Type": "LeastConnection"
      }
    }
  ],
  "GlobalConfiguration": {
    "ServiceDiscoveryProvider": {
      "Scheme": "http",
      "Host": "consul",
      "Port": 8500,
      "Type": "PollConsul"
    }
  }
```
  2. Docker composer file
 ```yaml
version: '3.4'

services:
     sharepoint.api:
        image: ${DOCKER_REGISTRY-}orderingapi
        hostname: sharepointapi
        build:
            context: .
            dockerfile: Sharepoint.API/Dockerfile
        ports:
            - "8002:80"

    private.gtw:
        image: ${DOCKER_REGISTRY-}privategtw
        build:
            context: .
            dockerfile: Private.Gtw/Dockerfile
       ports:
            - "7000:80"

    consul:
        image: consul:latest
        command: consul agent -dev -log-level=warn -ui -client=0.0.0.0 -bind='{{ GetPrivateIP }}'        
        hostname: consul
        ports:
            - "8500:8500"
 ```

  3. Startup file
``` C#
        public void ConfigureServices(IServiceCollection services)
        {
            services
                .AddOcelot()
                .AddConsul(); 
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });

            //ocelot
            app.UseOcelot().Wait();
        }
```
4. Output from Consul Monitor
```
/ # consul monitor
2020-09-01T06:54:40.712Z [INFO]  agent: Deregistered service: service=SharepointAPI
2020-09-01T06:54:40.911Z [INFO]  agent: Synced service: service=SharepointAPI
```

## Specifications

The service looks registered in the web client. 
If I **ping** beetwen the consul container, the private gateway and the service container they can be reached each other.

  - Nuget Ocelot Version: 16.0.1
  - Nuget Ocelot.Provider.Consul Version: 16.0.1
  - Nuget Consul Version: 1.6.1.1
  - Platform: Net Core 3.1
  - Subsystem: Windows 10

How can I solve this problem?
