### ISSUE TITLE
Adding a Target Port to Kubernetes Service Causes Service Discovery to Fail

### ISSUE THREAD

**Issue by matsch01** [ThreeMammals/Ocelot#1508]
## Expected Behavior / New Feature
When a targetPort is added to the Kubernetes service resource there should be no impact on Service Discovery.

```
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: my-app
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: web
  selector:
    app: my-app
```

## Actual Behavior / Motivation for New Feature
Ocelot fails to find the service:

2021-08-27 07:57:07.753 [Warning] () requestId: 0HMB95QFS8JPS:00000004, previousRequestId: no previous request id, message: Error Code: ServicesAreEmptyError Message: There were no services in NoLoadBalancer errors found in ResponderMiddleware. 

## Steps to Reproduce the Problem

  1. Add a targetPort to the Kubernetes service resource.

## Specifications

  - Version: 16.01
  - Platform: AspCore.Net 3.1
  - Subsystem:
