### ISSUE TITLE
Configuration reload is not working 

### ISSUE THREAD

**Issue by stg609** [ThreeMammals/Ocelot#663]
## Expected Behavior / New Feature
If I change the load balance option, the ocelot should using the updated option from next request.

## Actual Behavior / Motivation for New Feature
The next requests still use the original option.

## Steps to Reproduce the Problem
program.cs
```
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration(config =>
                {
                    config.AddJsonFile(Path.Combine("configuration", "configuration.json"), optional: false, reloadOnChange: true);
                })
                .UseStartup<Startup>();
    }
```
configuration/configuration.json, the load balancer option is **RoundRobin**
```
{
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/api/{everything}",
      "DownstreamScheme": "http",
      "ServiceName": "PostService",
      "LoadBalancerOptions": {
        "Type": "RoundRobin"
      },
      "UseServiceDiscovery": true,
      "UpstreamPathTemplate": "/post/api/{everything}",
      "UpstreamHttpMethod": [ "POST", "PUT", "GET" ]
    }
  ],
  "GlobalConfiguration": {
    "ServiceDiscoveryProvider": {
      "Host": "consul-server",
      "Port": 8500,
      "Type": "Consul"
    }
  }
}
```

1. Build a docker image using the dockerfile generated by the visual studio 2017.
2. Create a kubernete Configmap object using below command:
`kubectl create configmap ocelot-config-v1 --from-file=configuration/configuration.json`
3. create a deploy.yaml like below:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ocelot-kubernetes
  labels:
    app: ocelot-kuberentes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
     app: ocelot-kuberentes-pod
  template:
    metadata:
      labels:
        app: ocelot-kuberentes-pod
    spec:
      containers:
      - name: ocelot-kubernetes-containers
        image: "ocelotapigw:latest"
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 80
        volumeMounts:
          - name: ocelotconfig
            mountPath: /app/configuration/ 
      volumes:
        - name: ocelotconfig
          configMap:
            name: ocelot-config-v1
            items:
            - key: configuration.json
              path: configuration.json
```
4. Deploy the ocelot to kubernetes cluster using:
kubectl create -f deploy.yaml
5. Visit api gateway at http://host/post/api/values several times, I can see the internal api ip address is changed each time when I visit the api gateway from my log file.
6.  Change the load balancer option to **None**
kubectl edit configmap ocelot-config-v1
6. Wait for about 5 mins, then visit http://host/post/api/values several times. The internal ip address still get changed each time. 

## Specifications

  - Ocelot Version: 12.0.0
  - Kubernete Version: Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
  - Platform: Docker for windows and single node kubernete cluster
