### ISSUE TITLE
Doesn't reload config file in k8s

### ISSUE THREAD

**Issue by Marusyk** [ThreeMammals/Ocelot#684]
I'm using k8s to deploy image with Ocelot. I need to change route configs without restart Ocelot. So, from docs I found that:
```csharp
.AddJsonFile(Path.Combine("configurations", "ocelot.json"), true, true)
```
should work, but it doesn't.

## Steps to Reproduce the Problem

  1. Program.cs
```csharp
private static IWebHostBuilder CreateWebHostBuilder(string[] args)
{
	return WebHost.CreateDefaultBuilder(args)
		.ConfigureAppConfiguration((hostingContext, config) =>
		{
			config
				.SetBasePath(hostingContext.HostingEnvironment.ContentRootPath)
				.AddJsonFile("appsettings.json", true, true)
				.AddJsonFile(Path.Combine("configurations", "ocelot.json"), true, true)
				.AddEnvironmentVariables();
		})
		.UseStartup<Startup>();
}
```
  2. Create ConfigMap
```yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ocelot-api
  labels:
    module: ocelot
    app: api
data:
  ocelot: '{
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/{everything}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "users-api",
          "Port": 7511
        }
      ],
      "UpstreamPathTemplate": "/users/{everything}"
    }
  ]
}'
```
  3. A part of my Deployment

```yml
spec:
  containers:
  - name: master
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: Development
    image: apigateway-ocelot
    ports:
    - containerPort: 80
    volumeMounts:
    - name: config
       mountPath: /app/configurations
  volumes:
  - name: config
     configMap:
       name: ocelot-api
       items:
       - key: ocelot
         path: ocelot.json 
```
  4. Run. Everything works. But now I need to change a route in configMap and apply
```json
"UpstreamPathTemplate": "/usersnew/{everything}"
```
5. The mounted file is changed. But Ocelot returns 404 and old route works.

## Specifications

  - Version: 11.0.2
  - Platform: docker
  - Subsystem: k8s
